name: Build and Deploy Pelican Site

on:
  push:
    branches: [pages] # Changed from main to pages
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write # Needed for pushing to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Adjust to match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Pelican site
        run: |
          pelican content -o output -s pelicanconf.py

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output # Directory containing the built site
          branch: gh-pages # The branch the action should deploy to
          clean: true # Automatically remove deleted files from the deploy branch
